kind: pipeline
type: docker
name: default
steps:
  - name: lint
    image: denoland/deno:alpine
    commands:
      - deno fmt --check
      - deno lint
  - name: test
    image: denoland/deno:alpine
    commands:
      - deno test -A