version: 2
before:
  hooks:
    - make clean
    - go mod tidy
    - docs/prepare-packaging.sh
    - go mod vendor

builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - go_first_class
      # - plan9_amd64
      - freebsd_amd64

universal_binaries:
  - replace: true

archives:
  - files:
      - LICENSE
      - completions/**
      - docs/awl.1.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}MacOS_
      {{- else if eq .Os "freebsd" }}FreeBSD_
      {{- else }}{{- title .Os }}_{{ end }}
      {{- if eq .Arch "386" }}i386
      {{- else if eq .Arch "mips64" }}mips64_hardfloat
      {{- else if eq .Arch "mips64le" }}mips64le_hardfloat
      {{- else }}{{ .Arch }}{{ end -}}
    format_overrides:
      - goos: windows
        formats: zip
  - files:
      - vendor/**
    id: vendor
    formats: tar.xz
    name_template: "{{ .ProjectName }}-{{ .Version }}-deps"
    meta: true
    wrap_in_directory: "{{ .ProjectName }}"

nfpms:
  - id: packages
    package_name: awl-dns
    vendor: Sam Therapy <sam@samtherapy.net>
    maintainer: Sam Therapy <sam@samtherapy.net>
    homepage: https://dns.froth.zone/awl
    description: |-
      Command-line DNS query tool.
      Awl supports DNS-over-[UDP,TCP,HTTPS,QUIC] and DNSCrypt.
    license: BSD-3-Clause
    section: utils
    bindir: /usr/bin
    formats:
      - apk
      - archlinux
      - deb
      - rpm
    contents:
      - src: completions/bash.bash
        dst: /usr/share/bash-completion/completions/awl
      - src: docs/awl.1.gz
        dst: /usr/share/man/man1/awl.1.gz
      - src: completions/fish.fish
        dst: /usr/share/fish/vendor_completions.d/awl.fish
      # DEB only
      - src: LICENSE
        dst: /usr/share/doc/awl/copyright
        packager: deb
      - src: README.md.gz
        dst: /usr/share/doc/awl/README.md.gz
        packager: deb
      - src: docs/CONTRIBUTING.md.gz
        dst: /usr/share/doc/awl/CONTRIBUTING.md.gz
        packager: deb
      - src: completions/zsh.zsh
        dst: /usr/share/zsh/vendor-completions/_awl
        packager: deb
      # Alpine .apk only
      - src: completions/zsh.zsh
        dst: /usr/share/zsh/site-functions/_awl
        packager: apk
      # RPM only
      - src: LICENSE
        dst: /usr/share/licenses/awl/LICENSE
        packager: rpm
      - src: README.md
        dst: /usr/share/doc/awl/README.md
        packager: rpm
      - src: docs/CONTRIBUTING.md
        dst: /usr/share/doc/awl/CONTRIBUTING.md.gz
        packager: rpm
      - src: completions/zsh.zsh
        dst: /usr/share/zsh/site-functions/_awl
        packager: rpm
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
    overrides:
      deb:
        file_name_template: >-
          {{- .PackageName }}_
          {{- .Version }}_
          {{- if eq .Arch "386" }}i386
          {{- else if eq .Arch "arm" }}armel
          {{- else }}{{ .Arch }}{{ end -}}
      rpm:
        file_name_template: >-
          {{- .PackageName }}-
          {{- .Version }}-
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i686
          {{- else if eq .Arch "arm" }}armhfp
          {{- else if eq .Arch "arm64" }}aarch64
          {{- else }}{{ .Arch }}{{ end -}}
  - id: termux
    package_name: awl-dns
    vendor: Sam Therapy <sam@samtherapy.net>
    maintainer: Sam Therapy <sam@samtherapy.net>
    homepage: https://dns.froth.zone/awl
    description: |-
      Command-line DNS query tool.
      Awl supports DNS-over-[UDP,TCP,HTTPS,QUIC] and DNSCrypt.
    license: BSD-3-Clause
    section: utils
    formats:
      - termux.deb
    file_name_template: >-
      {{- .PackageName }}_
      {{- .Version }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i686
      {{- else if eq .Arch "arm" }}arm
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end -}}

snapcrafts:
  - name: awl-dns
    grade: stable
    publish: true
    summary: A command-line DNS query tool
    description: |-
      Awl is a command-line DNS query tool.
      Awl supports DNS-over-[UDP,TCP,HTTPS,QUIC] and DNSCrypt.
    confinement: strict
    license: BSD-3-Clause
    base: bare
    apps:
      awl-dns:
        command: awl
        plugs:
          - network
        completer: completions/bash.bash

dockers:
  - image_templates:
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest"
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

homebrew_casks:
  - repository:
      owner: packaging
      name: homebrew
    homepage: https://dns.froth.zone/awl
    description: A command-line DNS query tool
    license: BSD-3-Clause
    manpages:
      - "docs/awl.1.gz"
    completions:
      bash: "completions/bash.bash"
      zsh: "completions/zsh.zsh"
      fish: "completions/fish.fish"

nix:
  - repository:
      owner: packaging
      name: nur
    homepage: https://dns.froth.zone/awl
    description: A command-line DNS query tool
    license: bsd3
    extra_install: |-
      installManPage ./docs/awl.1.gz
      installShellCompletion ./completions/*

scoops:
  - repository:
      owner: packaging
      name: scoop
    directory: bucket
    homepage: https://dns.froth.zone/awl
    description: A command-line DNS query tool
    license: BSD-3-Clause

changelog:
  sort: asc
  groups:
    - title: "Dependency Updates"
      regexp: "^.*fix\\(deps\\)*:+.*$"
      order: 2
    - title: "Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Other"
      order: 999
  filters:
    exclude:
      - "^test:"
      - "^docs?:"
      - "typo"
      - "^ci:"

uploads:
  - name: packages
    method: PUT
    mode: archive
    exts:
      - deb
      - rpm
      - apk
      - termux.deb
    username: sam
    target: >-
      https://git.froth.zone/api/packages/sam/
      {{- if eq .ArtifactExt "deb" }}debian/pool/sid/main/upload
      {{- else if eq .ArtifactExt "termux.deb" }}debian/pool/termux/main/upload
      {{- else if eq .ArtifactExt "rpm" }}rpm/upload
      {{- else if eq .ArtifactExt "apk" }}alpine/edge/main{{ end -}}
    custom_artifact_name: true # Truncate the artifact name from the upload URL

gitea_urls:
  api: https://git.froth.zone/api/v1
  download: https://git.froth.zone
