# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - make clean
    - go mod tidy
    # Make manpages
    - doc/makeman.sh
    # Vendor dependencies
    - go mod vendor

builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - go_first_class
      - plan9_amd64
      - freebsd_amd64

archives:
  - files:
      - LICENCE
      - completions/**
      - doc/awl.1.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}MacOS_
      {{- else if eq .Os "freebsd" }}FreeBSD_
      {{- else }}{{- title .Os }}_{{ end }}
      {{- if eq .Arch "386" }}i386
      {{- else if eq .Arch "mips64" }}mips64_hardfloat
      {{- else if eq .Arch "mips64le" }}mips64le_hardfloat
      {{- else }}{{ .Arch }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
  - files:
      - vendor/**
    id: vendor
    format: tar.xz
    name_template: "{{ .ProjectName }}-{{ .Version }}-deps"
    meta: true
    wrap_in_directory: "{{ .ProjectName }}"

universal_binaries:
- replace: true

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc

  groups:
    - title: "Dependency Updates"
      regexp: "^.*fix\\(deps\\)*:+.*$"
      order: 2
    - title: "Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Other"
      order: 999

  filters:
    exclude:
      - "^test:"
      - "^docs?:"
      - "typo"
      - "^ci:"

brews:
  - repository:
      owner: packaging
      name: homebrew
    homepage: https://dns.froth.zone/awl
    description: A DNS query tool
    license: BSD-3-Clause
    # custom_block: |
    #   head "https://git.froth.zone/sam/awl.git"
    install: |-
      bin.install "awl"
      bash_completion.install "completions/bash.bash" => "awl"
      zsh_completion.install "completions/zsh.zsh" => "_awl"
      fish_completion.install "completions/fish.fish" => "awl.fish"
      man1.install "doc/awl.1.gz"

scoops:
  - repository:
      owner: packaging
      name: scoop
    folder: bucket
    homepage: https://dns.froth.zone/awl
    description: A DNS query client
    license: BSD-3-Clause

nix:
  -
    repository:
      owner: packaging
      name: nur
    homepage: https://dns.froth.zone/awl
    description: A DNS query client
    license: BSD-3-Clause
    extra_install:
      installManPage ./doc/awl.1.gz
    post_install: |
      installShellCompletion ./completions/*

nfpms:
  - id: packages
    package_name: awl-dns
    vendor: Sam Therapy <sam@samtherapy.net>
    maintainer: Sam Therapy <sam@samtherapy.net>
    homepage: https://dns.froth.zone/awl
    description: |-
      Command-line DNS query tool.
      Awl supports DNS-over-[UDP,TCP,HTTPS,QUIC] and DNSCrypt.
    license: BSD-3-Clause
    section: utils
    bindir: /usr/bin
    formats:
      - apk
      - archlinux
      - deb
      - rpm
    contents:
      - src: completions/bash.bash
        dst: /usr/share/bash-completion/completions/awl
      - src: doc/awl.1.gz
        dst: /usr/share/man/man1/awl.1.gz
      - src: LICENCE
        dst: /usr/share/doc/awl/copyright
      - src: completions/fish.fish
        dst: /usr/share/fish/vendor_completions.d/awl.fish
      # DEB only
      - src: completions/zsh.zsh
        dst: /usr/share/zsh/vendor-completions/_awl
        packager: deb
      # Alpine .apk only
      - src: completions/zsh.zsh
        dst: /usr/share/zsh/site-functions/_awl
        packager: apk
      # RPM only
      - src: completions/zsh.zsh
        dst: /usr/share/zsh/site-functions/_awl
        packager: rpm
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
    overrides:
      deb:
        file_name_template: >-
          {{- .PackageName }}_
          {{- .Version }}_
          {{- if eq .Arch "386" }}i386
          {{- else if eq .Arch "arm" }}armel
          {{- else }}{{ .Arch }}{{ end -}}
      rpm:
        file_name_template: >-
          {{- .PackageName }}-
          {{- .Version }}-
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i686
          {{- else if eq .Arch "arm" }}armhfp
          {{- else if eq .Arch "arm64" }}aarch64
          {{- else }}{{ .Arch }}{{ end -}}

  - id: termux
    package_name: awl-dns
    vendor: Sam Therapy <sam@samtherapy.net>
    maintainer: Sam Therapy <sam@samtherapy.net>
    homepage: https://dns.froth.zone/awl
    description: |-
      Command-line DNS query tool.
      Awl supports DNS-over-[UDP,TCP,HTTPS,QUIC] and DNSCrypt.
    license: BSD-3-Clause
    section: utils
    formats:
      - termux.deb
    file_name_template:  >-
          {{- .PackageName }}_
          {{- .Version }}_
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i686
          {{- else if eq .Arch "arm" }}arm
          {{- else if eq .Arch "arm64" }}aarch64
          {{- else }}{{ .Arch }}{{ end -}}

uploads:
  -
    name: packages
    method: PUT
    mode: archive
    exts:
      - deb
      - rpm
      - apk
      - termux.deb
    username: sam
    target: >-
      https://git.froth.zone/api/packages/sam/
      {{- if eq .ArtifactExt "deb" }}debian/pool/sid/main/upload
      {{- else if eq .ArtifactExt "termux.deb" }}debian/pool/termux/main/upload
      {{- else if eq .ArtifactExt "rpm" }}rpm/upload
      {{- else if eq .ArtifactExt "apk" }}alpine/edge/main{{ end -}}
    custom_artifact_name: true # Truncate the artifact name from the upload URL

gitea_urls:
  api: https://git.froth.zone/api/v1
  download: https://git.froth.zone
