name: Forgejo Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install scdoc
        run: apt-get update && apt-get install -y scdoc

      - name: Release with GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean -p 4 --skip snapcraft
        env:
          GORELEASER_FORCE_TOKEN: gitea
          GITEA_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          UPLOAD_PACKAGES_SECRET: ${{ secrets.PUBLISH_TOKEN }}
