name: Test
on: push

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        goVer: ["oldstable", "stable"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goVer }}

      - name: Test
        run: make test-ci
