name: Test
on: push

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        goVer: ["oldstable", "stable"]
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.goVer }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Test
        run: make test-ci
