# You may ask yourself, why make a snap?
# why not?

name: awl
base: core20
adopt-info: awl
license: BSD-3-Clause
summary: A command-line DNS query tool.
description: |
  awl is a command line DNS tool, much like dig and drill.

grade: devel
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: s390x
  - build-on: ppc64el
  - build-on: armhf

parts:
  awl:
    build-packages:
      - scdoc
    plugin: go
    source-type: git
    source: https://git.froth.zone/sam/awl
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --always | sed 's/\([^-]*-g\)/r\1/;s/-/./g' || echo 'UNKNOWN')"
    override-build: |
      HASH=$(git describe --always | sed 's/\([^-]*-g\)/r\1/;s/-/./g' || echo 'UNKNOWN')+snap make
      PREFIX=$SNAPCRAFT_PART_INSTALL make install

apps:
  awl:
    command: bin/awl
    completer: share/bash-completion/completions/awl
    plugs:
      - network